spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: stock-service

server:
  port: 9001
  
---
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: email-service

server:
  port: 9002
---
